name: CI
on:
  pull_request:
    branches: [feature_branch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies, checkout codes
        uses: actions/checkout@v3
      - name: Install NPM dependencies
        run: npm ci
      - name: Check code formatting
        run: npm run format:check
      - name: Run test
        run: run test -- --coverage
        env:
          CI: true
