name: "Unit Test"

on:
  push:
    
jobs:
  build:
    
    runs-on: ${{ matrix.os }}-latest
    
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    
    steps:
    - name: "npm test"
      run: |
        npm test
