name: "Unit Test"

# REPLACE THESE WITH GITHUB SECRETS LATER
env:
  CONTENTFUL_TOKEN: 9f-XGKwmXr533vwCzH0ae7splSEDFv7pW2XZlYvoceE
  CONTENTFUL_SPACE: zp1ezqte84g5
  MONGODB_URI: mongodb+srv://amazona:GXv15QKXZC7iMfSe@cluster0.9fhufmm.mongodb.net/amazona?retryWrites=true&w=majority

on:
  push:
  pull_request:
    
jobs:
  build-windows:
    
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: "npm test"
      working-directory: "./"
      run: |
        npm install
        npm test
  
  build-macos:
    
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: "npm test"
      working-directory: "./"
      run: |
        npm install
        npm test
  
  build-ubuntu:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: "npm test"
      working-directory: "./"
      run: |
        npm install
        npm test
